	AREA RESET, DATA, READONLY
    EXPORT  __Vectors

__Vectors 
	DCD  0x40001000     ; stack pointer value when stack is empty
    DCD  Reset_Handler  ; reset vector
  
	ALIGN
	AREA mycode, CODE, READONLY
	ENTRY
	EXPORT Reset_Handler
		
Reset_Handler
	LDR R0,=V1
	MOV R7,R0; ARRAY POINTER FOR J VARIABLE
	LDR R1,=ANS
	;LDR R2,[R0]
	LDR R3,[R1]
	MOV R4,#5; SIZE OF THE ARRAY FOR I LOOP
	MOV R9,#4; SIZE OF THE ARRAY FOR J LOOP
	MOV R10,#0; STORE THE POSITION
	MOV R5,#9999; STORE THE MIN VALUE
	MOV R6,#0; J VARIABLE VALUE
ILOOP
	LDR R2,[R0]
	MOV R7,R0; J=I+1
	ADD R7,#4
	MOV R9,R4
	SUB R9,#1
	MOV R5,R2
	CMP R9,#0
	BEQ CONT
	
JLOOP
	LDR R6,[R7]
	CMP R6,R5
	BLT SWAP
	BGE PASS
SWAP
	MOV R10,R7
	MOV R5,R6
PASS
	SUB R9,#1
	ADD R7,#4
	CMP R9,#0
	BGT JLOOP
	; R10 POINTS TO LEAST ELE, R5 HOLDS LEAST ELE, R2 HOLDS FIRST ELE
	CMP R2,R5
	BNE DIFF
	BEQ CONT
DIFF
	STR R2, [R10]
	STR R5,[R0]
CONT
	STR R5,[R1],#4
	SUB R4,#1
	ADD R0,#4
	MOV R5,#9999
	CMP R4,#0
	BGT ILOOP
	
	
	

	
	
STOP B STOP



	AREA MY_DATA, DATA, READWRITE	
V1 DCD 4,5,3,2,1

ANS DCD 0

	END